"""The ``.replico/`` store.

Everything written to disk passes through the security sanitizer. The store
layout is fixed (documented in README):

    .replico/
    ├── environment.json    local environment fingerprint (names only)
    ├── reproduction.json   machine-readable reproduction record
    ├── workflow.yml        redacted copy of the workflow file
    ├── commands.txt        the exact commands that were (and will be) run
    ├── differences.json    CI vs local differences + parity estimate
    ├── whyfail.json        structured WhyFail diagnosis (when one exists)
    └── README.md           human summary of the reproduction
"""

from __future__ import annotations

import contextlib
import json
from datetime import UTC, datetime
from pathlib import Path

from replico.errors import InvalidInputError
from replico.security.redaction import Sanitizer
from replico.util import find_upwards

STORE_DIRNAME = ".replico"
FORMAT_VERSION = 1

STORE_FILES = (
    "environment.json",
    "reproduction.json",
    "workflow.yml",
    "commands.txt",
    "differences.json",
    "whyfail.json",
    "README.md",
)

_README_TEMPLATE = """# Replico reproduction

This directory was generated by Replico on {created} to reproduce a GitHub
Actions failure locally. Treat it as a build artifact: add `{store}/` to
your `.gitignore` and delete it with `replico clean` when done.

What was reproduced
-------------------
{verdict_summary}

Run again after a code change
-----------------------------
    replico rerun

See the state of this reproduction
----------------------------------
    replico status
    replico diff

Files
-----
- reproduction.json  — machine-readable record (redacted)
- environment.json   — local environment fingerprint (no secret values)
- differences.json   — CI vs local differences and parity estimate
- workflow.yml       — redacted copy of the workflow that failed
- commands.txt       — exact setup and target commands used
- whyfail.json       — structured WhyFail diagnosis of the local failure
                      (present only when a Python failure was diagnosed)

Security
--------
Values that look like secrets are redacted before anything is written here.
WhyFail runs locally and its diagnostics are re-sanitized on the way in.
"""


class ReproductionStore:
    """Reads/writes a ``.replico`` directory under ``root``."""

    def __init__(self, root: Path, sanitizer: Sanitizer | None = None) -> None:
        self.root = Path(root)
        self.dir = self.root / STORE_DIRNAME
        self._sanitizer = sanitizer or Sanitizer()

    # -- discovery ------------------------------------------------------------

    @staticmethod
    def locate(start: Path | None = None) -> Path | None:
        found = find_upwards(STORE_DIRNAME, start)
        return found if found and found.is_dir() else None

    def exists(self) -> bool:
        return (self.dir / "reproduction.json").is_file()

    # -- payload --------------------------------------------------------------

    @staticmethod
    def _sanitize_mapping(mapping: dict, sanitizer: Sanitizer) -> dict:
        import copy

        out = copy.deepcopy(mapping)

        def walk(value):
            if isinstance(value, dict):
                return {k: walk(v) for k, v in value.items()}
            if isinstance(value, list):
                return [walk(v) for v in value]
            if isinstance(value, str):
                return sanitizer.redact(value)
            return value

        return walk(out)

    def write(self, payload: dict) -> None:
        """Persist a full reproduction payload (see pipeline.build_store_payload)."""
        self.dir.mkdir(parents=True, exist_ok=True)
        payload = {**payload, "format_version": FORMAT_VERSION}
        payload.setdefault("created_at", datetime.now(UTC).isoformat())

        reproduction = self._sanitize_mapping(
            {
                key: value
                for key, value in payload.items()
                if key not in ("workflow_yaml", "setup_commands", "target_commands")
            },
            self._sanitizer,
        )
        self._write_json("reproduction.json", reproduction)

        environment = self._sanitize_mapping(payload.get("environment", {}), self._sanitizer)
        self._write_json("environment.json", environment)

        differences = self._sanitize_mapping(payload.get("differences", []), self._sanitizer)
        self._write_json("differences.json", differences)

        workflow_yaml = self._sanitizer.redact(payload.get("workflow_yaml", ""))
        (self.dir / "workflow.yml").write_text(workflow_yaml, encoding="utf-8")

        commands = payload.get("setup_commands", []) + payload.get("target_commands", [])
        commands_text = "\n\n".join(
            f"# {entry.get('comment', '')}\n{entry.get('text', '')}"
            for entry in commands
            if entry.get("text")
        )
        (self.dir / "commands.txt").write_text(
            self._sanitizer.redact(commands_text), encoding="utf-8"
        )

        verdict = payload.get("verdict") or {}
        summary = verdict.get("summary") or payload.get("summary") or ""
        readme = _README_TEMPLATE.format(
            created=reproduction.get("created_at", "?"),
            verdict_summary=summary,
            store=STORE_DIRNAME,
        )
        (self.dir / "README.md").write_text(self._sanitizer.redact(readme), encoding="utf-8")

    def _write_json(self, name: str, data) -> None:
        text = json.dumps(data, indent=2, default=str)
        (self.dir / name).write_text(self._sanitizer.redact(text), encoding="utf-8")

    # -- reading --------------------------------------------------------------

    def read(self) -> dict:
        path = self.dir / "reproduction.json"
        if not path.is_file():
            raise InvalidInputError(
                f"no saved reproduction found at {self.dir} (run `replico <run-url>` first)"
            )
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, ValueError) as exc:
            raise InvalidInputError(
                f"saved reproduction at {self.dir} is unreadable ({exc}); "
                "run `replico clean` and reproduce again"
            ) from exc
        if data.get("format_version") != FORMAT_VERSION:
            raise InvalidInputError(
                f"saved reproduction uses format v{data.get('format_version')} "
                f"but this Replico reads v{FORMAT_VERSION}; run `replico clean` "
                "and reproduce again"
            )
        return data

    def read_commands(self) -> list[dict]:
        data = self.read()
        return data.get("setup_commands", []) + data.get("target_commands", [])

    def read_workflow_yaml(self) -> str:
        path = self.dir / "workflow.yml"
        if path.is_file():
            return path.read_text(encoding="utf-8")
        return ""

    def clean(self) -> None:
        """Remove the whole store directory (destructive — caller confirms)."""
        import shutil

        if self.dir.exists():
            shutil.rmtree(self.dir, ignore_errors=False)

    def render_commands_txt(self, setup: list[dict], target: list[dict]) -> str:
        entries = setup + target
        return "\n\n".join(
            f"# {entry.get('comment', '')}\n{entry.get('text', '')}"
            for entry in entries
            if entry.get("text")
        )

    # -- whyfail artifact -----------------------------------------------------

    def write_whyfail(self, doc: dict) -> None:
        """Persist the structured WhyFail artifact (sanitized)."""
        self.dir.mkdir(parents=True, exist_ok=True)
        self._write_json("whyfail.json", doc)

    def read_whyfail(self) -> dict | None:
        """Read the saved WhyFail artifact; None when absent or unreadable."""
        path = self.dir / "whyfail.json"
        if not path.is_file():
            return None
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, ValueError):
            return None
        return data if isinstance(data, dict) else None

    def remove_whyfail(self) -> None:
        path = self.dir / "whyfail.json"
        if path.is_file():
            with contextlib.suppress(OSError):
                path.unlink()
